services:
  web:
    ports:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles

nginx:
  image: alpine
  entrypoint: ["tail", "-f", "/dev/null"]
  ports: !reset []
  volumes: !reset []
  depends_on: !reset []