# Generated by Django 5.1 on 2026-02-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("llm", "Large Language Model"),
                            ("multimodal", "Multimodal"),
                            ("embedding", "Embedding"),
                            ("classifier", "Classifier"),
                            ("predictor", "Predictor"),
                            ("anomaly", "Anomaly Detector"),
                            ("recommender", "Recommender"),
                            ("ner", "NER Model"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "parameter_count",
                    models.BigIntegerField(
                        blank=True, help_text="Number of parameters", null=True
                    ),
                ),
                (
                    "context_window_size",
                    models.IntegerField(
                        blank=True, help_text="Context window size in tokens", null=True
                    ),
                ),
                ("training_cutoff_date", models.DateField(blank=True, null=True)),
                ("training_includes_pii", models.BooleanField(default=False)),
                ("training_includes_govt_data", models.BooleanField(default=False)),
                (
                    "explainability_level",
                    models.CharField(
                        choices=[
                            ("black_box", "Black Box"),
                            ("partial", "Partial Explainability"),
                            ("full", "Full Explainability"),
                        ],
                        default="black_box",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "custom_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional key/value attributes",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "ordering": ["name", "version"],
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("department", "Government Department"),
                            ("vendor", "Vendor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "deployment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cloud", "Cloud"),
                            ("on_premise", "On-Premise"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "licensing_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("commercial", "Commercial"),
                            ("open_source", "Open Source"),
                            ("in_house", "In-House"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product", "Product"),
                            ("service", "Service"),
                            ("platform", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("under_review", "Under Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ardoq_link",
                    models.URLField(blank=True, help_text="Link to record in Ardoq"),
                ),
                (
                    "informatica_link",
                    models.URLField(
                        blank=True, help_text="Link to dataset in Informatica"
                    ),
                ),
                (
                    "contract_link",
                    models.URLField(blank=True, help_text="Link to contract in Atamis"),
                ),
                ("data_residency", models.CharField(blank=True, max_length=255)),
                (
                    "security_certification",
                    models.CharField(blank=True, max_length=255),
                ),
                ("last_assessment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("custom_attributes", models.JSONField(blank=True, default=dict)),
                (
                    "ai_models",
                    models.ManyToManyField(
                        blank=True, related_name="tools", to="catalogue.aimodel"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools",
                        to="catalogue.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Tool / Platform",
                "verbose_name_plural": "AI Tools / Platforms",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developed_models",
                to="catalogue.organisation",
            ),
        ),
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "autonomy_level",
                    models.CharField(
                        choices=[
                            ("human_driven", "Human-Driven"),
                            ("human_in_loop", "Human-in-Loop"),
                            ("human_on_loop", "Human-on-Loop"),
                            ("autonomous", "Autonomous"),
                        ],
                        default="human_in_loop",
                        max_length=20,
                    ),
                ),
                ("human_in_loop", models.BooleanField(default=True)),
                ("is_public_facing", models.BooleanField(default=False)),
                ("impacted_population", models.TextField(blank=True)),
                ("custom_attributes", models.JSONField(blank=True, default=dict)),
                (
                    "owning_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="use_cases",
                        to="catalogue.organisation",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="use_cases",
                        to="catalogue.aitool",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("sro", "Senior Responsible Owner"),
                            ("dpo", "Data Protection Officer"),
                            ("security", "Security Officer"),
                            ("ethics", "Ethics Officer"),
                            ("architect", "Technical Architect"),
                            ("legal", "Legal Counsel"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="catalogue.aitool",
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="catalogue.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["role_type", "person_name"],
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attestation_type",
                    models.CharField(
                        choices=[
                            ("dpia", "DPIA"),
                            ("bias", "Bias Assessment"),
                            ("security", "Security Review"),
                            ("ethics", "Ethics Review"),
                            ("legal", "Legal Review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True)),
                ("attestation_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="catalogue.aitool",
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="catalogue.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-attestation_date"],
            },
        ),
    ]
