# Generated by Django 5.1 on 2026-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usecase",
            name="tool",
        ),
        migrations.AddField(
            model_name="usecase",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="use_cases", to="catalogue.aitool"
            ),
        ),
    ]
